[package]
name = "query_s3"
version = "0.1.0"
authors = ["Corby Shaner <Corby.Shaner@finra.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusoto_core = "0.41.0"
rusoto_s3 = "0.41.0"